services:
  mongo_db:
    image: mongo:latest
    container_name: "mongo_db"
    hostname: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=local
      - MONGO_INITDB_ROOT_PASSWORD=local
      - MONGO_INITDB_DATABASE=payments
    networks:
      - mynet
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=username
      - RABBITMQ_DEFAULT_PASS=password
    volumes:  
      - ../rabbitmq/data/:/var/lib/rabbitmq/
      - ../rabbitmq/log/:/var/log/rabbitmq
    networks:
      - mynet
  #ejercicio-rabbitmq:
  #  build:
  #    context: ./
  #    dockerfile: Dockerfile
  #  container_name: ejercicio-rabbitmq
  #  restart: always
  #  ports:
  #    - "8086:8086"
  #  image: ejercicio-rabbitmq
  #  environment:
  #    SPRING_RABBITMQ_HOST: rabbitmq
  #    SPRING_RABBITMQ_PORT: 5672
  #    SPRING_RABBITMQ_USERNAME: username
  #    SPRING_RABBITMQ_PASSWORD: password
  #    ME_CONFIG_MONGODB_ADMINUSERNAME: local
  #    ME_CONFIG_MONGODB_ADMINPASSWORD: local
  #    SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/payments?authSource=admin
  #  depends_on:
  #    - rabbitmq
  #    - mongo_db
  #  links:
  #    - rabbitmq
  #    - mongo_db
networks:
  mynet:
    driver: bridge